name: Deploy release pages with GitHub Pages

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build page
        shell: bash
        run: |       
          echo "Starte build..."
          
          cd gh-pages
          
          echo "1"
          
          ./create-pages.sh
          
          echo "2"
          
          mkdir output
          
          echo "3"
          
          cp all.html output
          cp releases.html output
          cp addons.html output
          cp images.html output
          
          echo "Ende"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
